kind: PersistentVolume
apiVersion: v1
metadata:
  name: oauth-mysql-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath: # If node goes down - all data is lost, PV should be external in production environment
    path: "/mnt/oauth-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: oauth-mysql-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

