apiVersion: v1
kind: Service
metadata:
  name: oauth-mysql
spec:
  ports:
  - port: 3306
  selector:
    app: oauth-mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: oauth-mysql
spec:
  selector:
    matchLabels:
      app: oauth-mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: oauth-mysql
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        env:
        - name: MYSQL_DATABASE
          value: oauth2
        - name: MYSQL_ROOT_USER
          value: root
          # Use secret in real usage
        - name: MYSQL_ROOT_PASSWORD
          value: secret
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: oauth-mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: oauth-mysql-persistent-storage
        persistentVolumeClaim:
          claimName: oauth-mysql-pv-claim
