apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: oauth-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oauth-server
  template: 
    metadata:
      labels:
        app: oauth-server
    spec:  
      containers:
      - name: oauth-server-2
        image: princetonplainsboro/oauth-authorization-server
        imagePullPolicy: Always
        env:
        - name: OAUTH2_DB_URL
          value: oauth-mysql
        - name: OAUTH2_DB_PORT
          value: "3306"
        - name: OAUTH2_DB_USER
          value: root
        - name: OAUTH2_DB_PASS
          value: secret
        args: ["--spring.profiles.active=prod"]   
        ports:
        - containerPort: 8090
          name: http

