# TODO:
# Extend docker-compose.yml
version: '2.1'
volumes:
 oauth2-mysql-data:
 hospital-service-data:

services:
  frontend:
    image: "princetonplainsboro/ng-hospital-frontend:latest"
    ports:
      - "8082:80"

  oauth2:
    image: "princetonplainsboro/oauth-authorization-server:latest"
    environment:
    - OAUTH2_DB_USER=root
    - OAUTH2_DB_PASS=secret
    - OAUTH2_DB_URL=oauth2-mysql
    - OAUTH2_DB_PORT=3306
    command: ["--spring.profiles.active=prod"]
    ports:
    - "8090:8090"
    depends_on:
      oauth2-mysql:
        condition: service_healthy

  oauth2-mysql:
    image: mysql:5.7
    container_name: oauth2-mysql
    volumes:
      - oauth2-mysql-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=oauth2
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - "33061:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
  
  hospital:
    image: "princetonplainsboro/hospital-service:latest"
    environment:
      - HOSPITAL_DB_USERNAME=root
      - HOSPITAL_DB_PASSWORD=admin
      - HOSPITAL_DB_URL=hospital-mysql
      - HOSPITAL_DB_PORT=3306
    command: ["--spring.profiles.active=prod"]
    ports:
      - "8000:8000"
    depends_on:
      hospital-mysql:
       condition: service_healthy
  
  hospital-mysql:
    image: mysql:5.7
    container_name: hospital-mysql
    volumes:
      - hospital-service-data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_DATABASE=hospital-mysql
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=admin
    ports:
      - "33062:3306"
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
   
  skin-lesion-service:
    image: "princetonplainsboro/skin-lesion-detection-service:latest"
    ports: 
      - "9000:9000" 
