apiVersion: extensions/v1beta1
kind: Deployment
metadata:
   name: hospital-pod
spec: 
   replicas: 1
   selector:
      matchLabels:
         app: hospital-backend
   template:
      metadata:
         labels:
            app: hospital-backend
      spec:
         containers:
         - name: hospital-service
           image: princetonplainsboro/hospital-service
           imagePullPolicy: Always
           ports:
           - containerPort: 8000
             name: http
             