apiVersion: v1
kind: Service
metadata:
   name: lesion-detection
spec:
   type: LoadBalancer
   ports:
   - port: 9000
     targetPort: 9000
     protocol: TCP
   selector:
     app: lesion-detection
